import React from "react";
import { Globe, Search, FileText, Database, Calendar, CheckCircle } from "lucide-react";

export type StepId =
  | "basics"
  | "discovery_setup"
  | "extraction_setup"
  | "llm"
  | "schedule"
  | "review";

export interface StepConfig {
  id: StepId;
  label: string;
  icon: React.ElementType;
  description: string;
}

export const ALL_STEPS: StepConfig[] = [
  { 
    id: "basics", 
    label: "Source Setup", 
    icon: Globe, 
    description: "Source information and basic setup"
  },
  { 
    id: "discovery_setup", 
    label: "Find Jobs", 
    icon: Search, 
    description: "Configure how to find job URLs"
  },
  { 
    id: "extraction_setup", 
    label: "Extract Details", 
    icon: FileText, 
    description: "Configure how to extract job details"
  },
  { id: "llm", label: "LLM Parsing", icon: Database, description: "Configure AI-powered data parsing" },
  { 
    id: "schedule", 
    label: "Schedule", 
    icon: Calendar, 
    description: "Set up discovery schedule and rate limits"
  },
  { 
    id: "review", 
    label: "Review", 
    icon: CheckCircle, 
    description: "Review and create source"
  }
];

export const LLM_MODELS = [
  { id: "gpt-4o-mini", name: "GPT-4o Mini", provider: "OpenAI", cost: "Low", speed: "Fast" },
  { id: "gpt-4o", name: "GPT-4o", provider: "OpenAI", cost: "High", speed: "Medium" },
  { id: "claude-3-haiku", name: "Claude 3 Haiku", provider: "Anthropic", cost: "Low", speed: "Fast" },
  { id: "claude-3-sonnet", name: "Claude 3 Sonnet", provider: "Anthropic", cost: "Medium", speed: "Medium" },
  { id: "claude-3-opus", name: "Claude 3 Opus", provider: "Anthropic", cost: "High", speed: "Slow" }
];

// Schema field configuration for LLM output
export interface SchemaFieldConfig {
  used: boolean;           // Whether field should be included in LLM output schema
  mandatory: boolean;      // Whether LLM must provide this field
  instructions: string;    // Instructions for LLM on how to extract this field
  dataType: string;        // Data type description
  example?: string;        // Example value for this field
}

// System field configuration for database fields that don't need LLM parsing
export interface SystemFieldConfig {
  dataType: string;        // Data type description
  description: string;     // What this field contains
  autoGenerated: boolean;  // Whether field is automatically populated by system
  example?: string;        // Example value for this field
}

// Complete schema with all job variables you specified
export const FULL_JOB_SCHEMA: Record<string, SchemaFieldConfig> = {
  title: {
    used: true,
    mandatory: true,
    instructions: "Extract the job title from the posting. This is usually prominently displayed at the top.",
    dataType: "string",
    example: "E-Commerce Manager"
  },
  locations: {
    used: true,
    mandatory: false,
    instructions: "Extract all work locations mentioned. Often multiple cities/offices are listed.",
    dataType: "array of strings",
    example: "Stockholm, Norrköping"
  },
  officePolicy: {
    used: true,
    mandatory: false,
    instructions: "Look for remote work policy - in office, hybrid, or remote arrangements.",
    dataType: "string (In office|Hybrid|Remote)",
    example: "Hybrid"
  },
  startDate: {
    used: true,
    mandatory: false,
    instructions: "Extract start date if specified. Look for 'ASAP' or specific dates.",
    dataType: "ISO date string",
    example: "2025-10-01"
  },
  asapStart: {
    used: true,
    mandatory: false,
    instructions: "Boolean flag if start date is 'ASAP' or immediate.",
    dataType: "boolean",
    example: "false"
  },
  assignmentLength: {
    used: true,
    mandatory: false,
    instructions: "Total assignment duration including extensions, usually in months.",
    dataType: "string",
    example: "12 months"
  },
  requirements: {
    used: true,
    mandatory: false,
    instructions: "List all required skills, technologies, and qualifications mentioned.",
    dataType: "array of strings",
    example: "Shopify, Google Analytics, SEO, SEM"
  },
  niceToHave: {
    used: true,
    mandatory: false,
    instructions: "Extract nice-to-have or preferred skills that are not mandatory.",
    dataType: "array of strings",
    example: "Python, Photoshop, Klaviyo"
  },
  description: {
    used: true,
    mandatory: false,
    instructions: "Main job description paragraph summarizing the role and responsibilities.",
    dataType: "string",
    example: "Assignment covers parental leave..."
  },
  descriptionList: {
    used: true,
    mandatory: false,
    instructions: "Extract bullet points or key responsibilities as separate items.",
    dataType: "array of strings",
    example: "Responsibility for online sales, Improve conversion"
  },
  category: {
    used: true,
    mandatory: false,
    instructions: "Primary job category that matches site navigation categories.",
    dataType: "string",
    example: "Sales & Marketing"
  },
  subcategory: {
    used: true,
    mandatory: false,
    instructions: "More specific subcategory within the main category.",
    dataType: "string",
    example: "E-commerce"
  },
  broker: {
    used: true,
    mandatory: false,
    instructions: "Name of the consulting firm or recruitment agency posting the job.",
    dataType: "string",
    example: "Emagine"
  },
  detailsLink: {
    used: false,
    mandatory: false,
    instructions: "Automatically populated with the URL from the discovery step - no LLM parsing needed.",
    dataType: "string (URL)",
    example: "https://portal.emagine.org/jobs/170116"
  },
  acceptingApplications: {
    used: true,
    mandatory: false,
    instructions: "Whether the position is currently accepting new applications.",
    dataType: "boolean",
    example: "true"
  },
  endClient: {
    used: true,
    mandatory: false,
    instructions: "The final client company (often different from the broker). May be unknown.",
    dataType: "string",
    example: "Polarn O. Pyret"
  },
  applyBy: {
    used: true,
    mandatory: false,
    instructions: "Application deadline if specified in the posting.",
    dataType: "ISO date string",
    example: "2025-10-01"
  },
  workload: {
    used: true,
    mandatory: false,
    instructions: "Percentage of full-time work expected (e.g., 100%, 75%, 50%).",
    dataType: "string (percentage)",
    example: "100%"
  },
  hourlyRate: {
    used: true,
    mandatory: false,
    instructions: "Hourly compensation rate in SEK if mentioned.",
    dataType: "string",
    example: "1050 SEK"
  },
  maxHourlyRate: {
    used: true,
    mandatory: false,
    instructions: "Maximum hourly rate if a range is specified.",
    dataType: "string",
    example: "1200 SEK"
  },
  seniorityLevel: {
    used: true,
    mandatory: false,
    instructions: "Experience level: 1-2 = Junior, 3-4 = Mid, 5 = Senior",
    dataType: "number (1-5)",
    example: "3"
  },
  compensationModel: {
    used: true,
    mandatory: false,
    instructions: "How compensation is structured - hourly or per project.",
    dataType: "string (Hour|Per project)",
    example: "Hour"
  }
};

// System-managed database fields (not requiring LLM parsing)
export const SYSTEM_DATABASE_FIELDS: Record<string, SystemFieldConfig> = {
  // Core Identification
  id: {
    dataType: "string (UUID)",
    description: "Unique job identifier generated by the system",
    autoGenerated: true,
    example: "uuid-123-456-789"
  },
  sourceId: {
    dataType: "string (UUID)", 
    description: "ID of the scraper source that discovered this job",
    autoGenerated: true,
    example: "source-abc-def-123"
  },
  detailsLink: {
    dataType: "string (URL)",
    description: "Original URL from discovery step - where the job was found",
    autoGenerated: true,
    example: "https://portal.emagine.org/jobs/170116"
  },

  // Tracking & Lifecycle
  firstSeen: {
    dataType: "ISO datetime string",
    description: "When job was first discovered by any scraper run",
    autoGenerated: true,
    example: "2024-09-05T14:23:15.123Z"
  },
  lastScraped: {
    dataType: "ISO datetime string",
    description: "Last time content was extracted and processed",
    autoGenerated: true,
    example: "2024-09-05T16:45:32.456Z"
  },
  lastUpdated: {
    dataType: "ISO datetime string",
    description: "When any field in this record was last changed",
    autoGenerated: true,
    example: "2024-09-05T16:45:32.456Z"
  },
  scrapedCount: {
    dataType: "number",
    description: "How many times this job has been scraped/processed",
    autoGenerated: true,
    example: "3"
  },
  status: {
    dataType: "string (active|expired|removed|error)",
    description: "Current status of this job posting",
    autoGenerated: true,
    example: "active"
  },

  // Content Management
  contentHash: {
    dataType: "string (hash)",
    description: "SHA256 hash of scraped content to detect changes",
    autoGenerated: true,
    example: "a1b2c3d4e5f6..."
  },
  rawContent: {
    dataType: "text",
    description: "Original HTML/text content scraped from the page",
    autoGenerated: true,
    example: "<html><body>Job posting content...</body></html>"
  },
  contentSize: {
    dataType: "number (bytes)",
    description: "Size of scraped content in bytes",
    autoGenerated: true,
    example: "15420"
  },
  extractionVersion: {
    dataType: "string",
    description: "Version of extraction logic used for this job",
    autoGenerated: true,
    example: "v2.1.3"
  },
  
  // LLM Processing Metadata
  llmModel: {
    dataType: "string",
    description: "Which LLM model was used for content parsing",
    autoGenerated: true,
    example: "gpt-4o-mini"
  },
  llmTokensUsed: {
    dataType: "number",
    description: "Total tokens consumed by LLM for this extraction",
    autoGenerated: true,
    example: "1247"
  },
  llmCost: {
    dataType: "number (SEK)",
    description: "Actual cost in SEK for LLM processing of this job",
    autoGenerated: true,
    example: "0.0523"
  },

  // Quality & Monitoring
  extractionErrors: {
    dataType: "array of strings",
    description: "List of any errors encountered during LLM parsing",
    autoGenerated: true,
    example: '["Failed to parse salary range", "Missing end client info"]'
  },
  confidence: {
    dataType: "number (0-1)",
    description: "Overall extraction confidence score from LLM",
    autoGenerated: true,
    example: "0.85"
  },
  fieldConfidence: {
    dataType: "object",
    description: "Per-field confidence scores from LLM extraction",
    autoGenerated: true,
    example: '{"title": 0.95, "salary": 0.3, "requirements": 0.88}'
  },
  validationErrors: {
    dataType: "array of strings", 
    description: "Schema validation issues found after extraction",
    autoGenerated: true,
    example: '["Invalid date format in startDate", "Email format invalid"]'
  },
  isManuallyReviewed: {
    dataType: "boolean",
    description: "Whether a human has manually verified this job data",
    autoGenerated: false,
    example: "false"
  },
  reviewedBy: {
    dataType: "string",
    description: "Username of person who reviewed this job (if applicable)",
    autoGenerated: false,
    example: "pontus"
  },

  // Discovery Context
  discoveryMethod: {
    dataType: "string (api|rss|sitemap|html|js)",
    description: "Which discovery technique found this job URL",
    autoGenerated: true,
    example: "api"
  },
  discoveryRunId: {
    dataType: "string (UUID)",
    description: "ID of the specific discovery run that found this job",
    autoGenerated: true,
    example: "run-789-012-345"
  },
  urlDepth: {
    dataType: "number",
    description: "How deep in site hierarchy this URL was found (for crawling)",
    autoGenerated: true,
    example: "2"
  },
  referrerUrl: {
    dataType: "string (URL)",
    description: "Page that linked to this job (if found via crawling)",
    autoGenerated: true,
    example: "https://example.com/jobs/category/marketing"
  }
};

// Legacy schema for backward compatibility
export const DEFAULT_EXTRACTION_SCHEMA = {
  title: "string (required)",
  company: "string (required)", 
  location: "string",
  salary: "string",
  startDate: "ISO date string",
  requirements: "array of strings",
  description: "string"
};

export const STORAGE_KEY = 'new-source-draft';
